# fly.toml app configuration file generated for 04-udp on 2024-07-30T19:40:57+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '04-udp'
primary_region = 'lhr'

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  ECHO_PORT = 5000

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 5000
  protocol = "udp"

  [[services.ports]]
    port = "5000"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
